[package]
name = "Level-03-Match-and-Parse"
version = "0.1.0"
authors = ["Bumsoo Kim <cmng828rhuypqq@cau.ac.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"